%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "any"
    EXTERNAL_NET: "any"

app-layer:
  protocols:
    http:
      enabled: yes

logging:
  outputs:
    - file:
        enabled: yes
        filename: /var/log/suricata/eve.json
        types:
          - alert
          - http
